// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson657db8cfDecodeGithubComSvkiorPowgweyServerInternalModels(in *jlexer.Lexer, out *Quotes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(Quotes, 0, 0)
			} else {
				*out = Quotes{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Quote
			easyjson657db8cfDecodeGithubComSvkiorPowgweyServerInternalModels1(in, &v1)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson657db8cfEncodeGithubComSvkiorPowgweyServerInternalModels(out *jwriter.Writer, in Quotes) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			easyjson657db8cfEncodeGithubComSvkiorPowgweyServerInternalModels1(out, v3)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v Quotes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson657db8cfEncodeGithubComSvkiorPowgweyServerInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Quotes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson657db8cfEncodeGithubComSvkiorPowgweyServerInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Quotes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson657db8cfDecodeGithubComSvkiorPowgweyServerInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Quotes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson657db8cfDecodeGithubComSvkiorPowgweyServerInternalModels(l, v)
}
func easyjson657db8cfDecodeGithubComSvkiorPowgweyServerInternalModels1(in *jlexer.Lexer, out *Quote) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "language":
			out.Language = string(in.String())
		case "source":
			out.Source = string(in.String())
		case "quote":
			out.Quote = string(in.String())
		case "author":
			out.Author = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson657db8cfEncodeGithubComSvkiorPowgweyServerInternalModels1(out *jwriter.Writer, in Quote) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"language\":"
		out.RawString(prefix)
		out.String(string(in.Language))
	}
	{
		const prefix string = ",\"source\":"
		out.RawString(prefix)
		out.String(string(in.Source))
	}
	{
		const prefix string = ",\"quote\":"
		out.RawString(prefix)
		out.String(string(in.Quote))
	}
	{
		const prefix string = ",\"author\":"
		out.RawString(prefix)
		out.String(string(in.Author))
	}
	out.RawByte('}')
}
